[project]
authors = ["Tristan <tristan.manchester@diamond.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "CropVolumes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.2,<3"
matplotlib = ">=3.10.0,<4"
pillow = ">=11.1.0,<12"
tqdm = ">=4.67.1,<5"
tifffile = ">=2025.1.10,<2026"
